// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHv03r9D9vWPIN9zfNP78EGoppsIXRbJc',
    appId: '1:178008861046:web:b9765ac12654a304c63257',
    messagingSenderId: '178008861046',
    projectId: 'core-ims-83a43',
    authDomain: 'core-ims-83a43.firebaseapp.com',
    storageBucket: 'core-ims-83a43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7ZdFV12FYTIXdtbLBp_6lEDYGveRAYw',
    appId: '1:178008861046:android:5dc487fff4c58de9c63257',
    messagingSenderId: '178008861046',
    projectId: 'core-ims-83a43',
    storageBucket: 'core-ims-83a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0ihFScghwdnF3XH0PPXGFHlMCDVrLQY',
    appId: '1:178008861046:ios:4bd4300ab09ccc1dc63257',
    messagingSenderId: '178008861046',
    projectId: 'core-ims-83a43',
    storageBucket: 'core-ims-83a43.firebasestorage.app',
    iosBundleId: 'com.example.coreIms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0ihFScghwdnF3XH0PPXGFHlMCDVrLQY',
    appId: '1:178008861046:ios:4bd4300ab09ccc1dc63257',
    messagingSenderId: '178008861046',
    projectId: 'core-ims-83a43',
    storageBucket: 'core-ims-83a43.firebasestorage.app',
    iosBundleId: 'com.example.coreIms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHv03r9D9vWPIN9zfNP78EGoppsIXRbJc',
    appId: '1:178008861046:web:3b696831de2618f6c63257',
    messagingSenderId: '178008861046',
    projectId: 'core-ims-83a43',
    authDomain: 'core-ims-83a43.firebaseapp.com',
    storageBucket: 'core-ims-83a43.firebasestorage.app',
  );
}
